# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1922, 904)
        self.actionOpen_File = QAction(MainWindow)
        self.actionOpen_File.setObjectName(u"actionOpen_File")
        self.actionOpen_Folder = QAction(MainWindow)
        self.actionOpen_Folder.setObjectName(u"actionOpen_Folder")
        self.actionOpen_Recent = QAction(MainWindow)
        self.actionOpen_Recent.setObjectName(u"actionOpen_Recent")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionSave_Automatically = QAction(MainWindow)
        self.actionSave_Automatically.setObjectName(u"actionSave_Automatically")
        self.actionChange_output_folder = QAction(MainWindow)
        self.actionChange_output_folder.setObjectName(u"actionChange_output_folder")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionNext_Image = QAction(MainWindow)
        self.actionNext_Image.setObjectName(u"actionNext_Image")
        self.actionBack_Image = QAction(MainWindow)
        self.actionBack_Image.setObjectName(u"actionBack_Image")
        self.actionNext_label = QAction(MainWindow)
        self.actionNext_label.setObjectName(u"actionNext_label")
        self.actionNext_label.setShortcutVisibleInContextMenu(False)
        self.actionBack_label = QAction(MainWindow)
        self.actionBack_label.setObjectName(u"actionBack_label")
        self.actionEdit_Label = QAction(MainWindow)
        self.actionEdit_Label.setObjectName(u"actionEdit_Label")
        self.actionFinish_Edit = QAction(MainWindow)
        self.actionFinish_Edit.setObjectName(u"actionFinish_Edit")
        self.actionFinish_Label = QAction(MainWindow)
        self.actionFinish_Label.setObjectName(u"actionFinish_Label")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ScreenPic = QLabel(self.centralwidget)
        self.ScreenPic.setObjectName(u"ScreenPic")
        self.ScreenPic.setGeometry(QRect(56, 24, 1591, 904))
        self.ScreenPic.setLayoutDirection(Qt.LeftToRight)
        self.ScreenPic.setFrameShape(QFrame.Box)
        self.ScreenPic.setScaledContents(False)
        self.ScreenPic.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 2, 71, 16))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(144, 2, 71, 16))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(210, 2, 141, 16))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(407, 2, 161, 16))
        font2 = QFont()
        font2.setPointSize(9)
        self.label_4.setFont(font2)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(358, 2, 51, 16))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(560, 2, 81, 16))
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(650, 2, 55, 16))
        self.label_7.setFont(font2)
        self.header_Label = QLabel(self.centralwidget)
        self.header_Label.setObjectName(u"header_Label")
        self.header_Label.setGeometry(QRect(1655, 24, 258, 25))
        font3 = QFont()
        font3.setBold(True)
        self.header_Label.setFont(font3)
        self.header_Label.setAlignment(Qt.AlignCenter)
        self.header_Text = QLabel(self.centralwidget)
        self.header_Text.setObjectName(u"header_Text")
        self.header_Text.setGeometry(QRect(1655, 320, 258, 25))
        self.header_Text.setFont(font3)
        self.header_Text.setAlignment(Qt.AlignCenter)
        self.header_file = QLabel(self.centralwidget)
        self.header_file.setObjectName(u"header_file")
        self.header_file.setGeometry(QRect(1655, 700, 258, 25))
        self.header_file.setFont(font3)
        self.header_file.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(720, 2, 81, 16))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(820, 2, 81, 16))
        self.label_9.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1922, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Automatically)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNext_Image)
        self.menuFile.addAction(self.actionBack_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNext_label)
        self.menuFile.addAction(self.actionBack_label)
        self.menuEdit.addAction(self.actionEdit_Label)
        self.menuEdit.addAction(self.actionFinish_Edit)
        self.menuEdit.addAction(self.actionFinish_Label)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"AppLabelling", None))
        self.actionOpen_File.setText(QCoreApplication.translate("MainWindow", u"Open File", None))
#if QT_CONFIG(shortcut)
        self.actionOpen_File.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen_Folder.setText(QCoreApplication.translate("MainWindow", u"Open Folder", None))
#if QT_CONFIG(shortcut)
        self.actionOpen_Folder.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen_Recent.setText(QCoreApplication.translate("MainWindow", u"Open Recent", None))
#if QT_CONFIG(shortcut)
        self.actionOpen_Recent.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
#if QT_CONFIG(shortcut)
        self.actionSave_as.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_Automatically.setText(QCoreApplication.translate("MainWindow", u"Save Automatically", None))
        self.actionChange_output_folder.setText(QCoreApplication.translate("MainWindow", u"Change output folder", None))
#if QT_CONFIG(shortcut)
        self.actionChange_output_folder.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
#if QT_CONFIG(shortcut)
        self.actionClose.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.actionNext_Image.setText(QCoreApplication.translate("MainWindow", u"Next Image", None))
#if QT_CONFIG(shortcut)
        self.actionNext_Image.setShortcut(QCoreApplication.translate("MainWindow", u"E", None))
#endif // QT_CONFIG(shortcut)
        self.actionBack_Image.setText(QCoreApplication.translate("MainWindow", u"Back Image", None))
#if QT_CONFIG(shortcut)
        self.actionBack_Image.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionNext_label.setText(QCoreApplication.translate("MainWindow", u"Next Label", None))
#if QT_CONFIG(shortcut)
        self.actionNext_label.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.actionBack_label.setText(QCoreApplication.translate("MainWindow", u"Back label", None))
#if QT_CONFIG(shortcut)
        self.actionBack_label.setShortcut(QCoreApplication.translate("MainWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.actionEdit_Label.setText(QCoreApplication.translate("MainWindow", u"Edit Label", None))
#if QT_CONFIG(shortcut)
        self.actionEdit_Label.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionFinish_Edit.setText(QCoreApplication.translate("MainWindow", u"Finish Edit", None))
#if QT_CONFIG(shortcut)
        self.actionFinish_Edit.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.actionFinish_Label.setText(QCoreApplication.translate("MainWindow", u"Finish Label", None))
#if QT_CONFIG(shortcut)
        self.actionFinish_Label.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Return", None))
#endif // QT_CONFIG(shortcut)
        self.ScreenPic.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"ShortCut:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Picture:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Previous: Q, Next: E ", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u" Previous: A, Next: D", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Label:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Edit Label:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Ctrl + E", None))
        self.header_Label.setText(QCoreApplication.translate("MainWindow", u"Labels", None))
        self.header_Text.setText(QCoreApplication.translate("MainWindow", u"Texts", None))
        self.header_file.setText(QCoreApplication.translate("MainWindow", u"File name", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Finish Edit:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Ctrl + Enter", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

